import Header from "@/Components/Dashboard/Header";
import SideBar from "@/Components/Dashboard/Sidebar";
import "../globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="rtl" className="h-screen">
      <body className="bg-[#f1f2f7] h-full">
        <Header />
        <div className="flex flex-row pt-20">
          <SideBar />
          <main className="h-full mr-[210px] p-8 w-full">{children}</main>
        </div>
      </body>
    </html>
  );
}
